# Generated by Django 4.0.2 on 2022-03-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workout_image_workout_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
