# Generated by Django 4.0.2 on 2022-03-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_customerprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(default='default.png', upload_to='workout_images'),
        ),
    ]
