# Generated by Django 4.0.2 on 2022-03-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_workout_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='target',
            field=models.CharField(max_length=100),
        ),
    ]
