# Generated by Django 4.0.2 on 2022-03-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_workout_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
