# Generated by Django 4.0.2 on 2022-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_tag_workoutprogram_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='program',
            field=models.TextField(default='Brief workout description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(default='/media/workout_images/dumbell_default.png', upload_to='workout_images'),
        ),
    ]
