# Generated by Django 4.0.2 on 2022-03-31 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_customerprofile_workouts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='workouts',
            new_name='program',
        ),
    ]
