# Generated by Django 4.0.2 on 2022-04-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_rename_workouts_customerprofile_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(default='/workout_images/dumbell_default.png', upload_to='workout_images'),
        ),
    ]
