# Generated by Django 4.0.2 on 2022-04-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_alter_workout_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(blank=True, default='/workout_images/dumbell_default.png', null=True, upload_to='workout_images'),
        ),
    ]
